### PR TITLE
fix[GWELLS-2632]: Remove vue compat, disable certain vue3 incompatible components, install primevue

### LINKED ISSUE #2632: vue/compat breaks primevue components
**Describe the Bug**
certain buttons that are programed a specific way (@click) bootstrap and primevue components are failing

@submit and @reset event handlers were fixed, .prevent doesnt work anymore in vue compat/prime vue
taking that out fixed previous issues but not the @click issue. Vanilla HTM buttons still work. none of this is in Dev right now as it was discovered trying to implement other tickets. 

**what have we investigated**

**Ideas on what is causing this?**
A clear and concise description of what actually happens.

Confirm this task meets our team [**Definition of Ready (DoR)**](https://www.figma.com/board/XmNkN600aAVWFCBmSDdt10/Team-Documents?node-id=1-2&t=Xjd6nHZZ7YlnoOrD-4) before moving to the **Next Sprint** column.

Confirm this task meets our team [**Definition of Done (DoD)**](https://www.figma.com/board/XmNkN600aAVWFCBmSDdt10/Team-Documents?node-id=3-21&t=Xjd6nHZZ7YlnoOrD-4) before moving to the **Done** column.

### PR DESCRIPTION
**Pull request by wilwong89**
## Pull Request Standards

- [X] The title of the PR is accurate
- [X] The title includes the type of change [`HOTFIX`, `FEATURE`, `etc`]  
- [X] The PR title includes the ticket number in format of `[GWELLS-###]`
- [ ] Documentation is updated to reflect change [`README`, `functions`, `team documents`]

# Description

This PR includes the following proposed change(s):

- Remove Vue compat
- Remove/comment out code incompatible with Vue3
- npm install primevue

Notes: 
- AdvancedSearchFilter.vue has a null reference somewhere, rather than taking time to fix a component to be rewritten with Primevue I have commented it out of the component that contains it for now.
- Legal.vue had some base HTML warnings in docker console that didn't like 'ul' and 'li' elements inside 'p'. Changed 'p' to 'div' temporarily but will need restyling later

### CODE REVIEW

File: app/frontend/src/submissions/components/SubmissionForm/AquiferParameters.vue [hunk 1]
```diff
@@ -29,8 +29,7 @@ Licensed under the Apache License, Version 2.0 (the "License");
         <thead>
         </thead>
         <tbody>
-          <template v-for="(aquiferParameter, index) in aquiferParametersData" :key="`aquifer-param-${index}`">
-            <div class="bordered-table">
+          <template class="bordered-table" v-for="(aquiferParameter, index) in aquiferParametersData" :key="`aquifer-param-${index}`">
```
Comment (lunamoonmoon) [inline app/frontend/src/submissions/components/SubmissionForm/AquiferParameters.vue:32]: Is class="bordered-table" bootstrap?

**Review by lunamoonmoon — APPROVED** [review]
Looks good! Maybe we should make spike tickets for VueNoty and VueMoment?

File: app/frontend/src/submissions/components/SubmissionForm/AquiferParameters.vue (hunk 1 above)
Comment (raarielgrace) [reply app/frontend/src/submissions/components/SubmissionForm/AquiferParameters.vue:32]: Nope, it's defined further down the file

File: app/frontend/src/submissions/components/SubmissionForm/Casings.vue [hunk 2]
```diff
@@ -172,7 +172,6 @@ Licensed under the Apache License, Version 2.0 (the "License");
 </template>
 
 <script>
-import Vue from 'vue'
```
Comment (raarielgrace) [inline app/frontend/src/submissions/components/SubmissionForm/Casings.vue:175]: Do you know why Vue was imported here?

**Review by raarielgrace — APPROVED** [review]

File: app/frontend/src/submissions/components/SubmissionForm/Casings.vue (hunk 2 above)
Comment (wilwong89) [reply app/frontend/src/submissions/components/SubmissionForm/Casings.vue:175]: No, it wasn't used anywhere before either but it was causing troubles keeping it without compat.
