### PR TITLE
fix[GWELLS-2540]: Registry conversion to primevue componenets

### LINKED ISSUE #2540: Update components in registry view to PrimeVue 4 and to CompositionAPI
**Describe the task**
As updating to PrimeVue and CompositionAPI will both require rewriting most of the component, it is better to do that concurrently rather than two separate rewrites.

-> Create a sub-issue under this ticket for each component for tracking which components are in-progress or done.

**Components under registry**

- people
  - [ ] ApplicationAddEdit.vue
  - [ ] ApplicationDetail.vue
  - [ ] Notes.vue
  - [ ] OrganizationEdit.vue
  - [ ] OrganizationAdd.vue
  - [ ] PersonNotes.vue
  - [ ] PersonEdit.vue
  - [ ] PersonDocuments.vue
  - [ ] PersonDetail.vue
  - [ ] PersonAdd.vue
- Search
  - [ ] RegistryMap.vue
  - [ ] SearchHome.vue
  - [ ] SearchTable.vue
  - Table Helpers
    - [ ] DrillerSubactivity.vue
    - [ ] DrillerRegistrationStatus.vue
    - [ ] DrillerOrganization.vue
    - [ ] DrillerOrgAddress.vue
    - [ ] DrillerContactInfo.vue
    - [ ] DrillerCertAuth.vue
- [ ] Legal.vue

### PR DESCRIPTION
**Pull request by lunamoonmoon**
## Pull Request Standards

- [x] The title of the PR is accurate
- [x] The title includes the type of change [`HOTFIX`, `FEATURE`, `etc`]  
- [x] The PR title includes the ticket number in format of `[GWELLS-###]`
- [ ] Documentation is updated to reflect change [`README`, `functions`, `team documents`]

# Description

This PR includes the following proposed change(s):

- Changed bootstrap components to primevue equivalents
- Wilson's pr removing compat allows search functionality to work
- Screenshot 2026-04-23 at 11 27 07 AM
- Screenshot 2026-04-23 at 11 27 00 AM

### CODE REVIEW

File: app/frontend/src/common/inputFormatMixin.js [hunk 1]
```diff
@@ -1,9 +0,0 @@
-const inputFormatMixin = {
```
Comment (lunamoonmoon) [inline app/frontend/src/common/inputFormatMixin.js:1]: deleted because using primevue InputMask does the telephone formatting without needing this function

File: app/frontend/src/main.js [hunk 2]
```diff
@@ -80,11 +84,40 @@ app.use(VueNoty, {
...
+app.component("Checkbox", Checkbox);
+app.component("CheckboxGroup", CheckboxGroup);
+app.component("Form", Form);
+app.component("Listbox", Listbox);
+app.component("ProgressSpinner", ProgressSpinner)
+app.component("Breadcrumb", Breadcrumb)
+app.component("Dialog", Dialog)
+app.component("DataTable", DataTable)
+app.component("Column", Column)
+app.component("FileUpload", FileUpload)
```
Comment (lunamoonmoon) [inline app/frontend/src/main.js:118]: importing and adding components globally in main

File: app/frontend/src/submissions/components/SubmissionForm/AquiferData.vue [hunk 3]
```diff
@@ -80,12 +80,11 @@ import { useSubmissionStore } from '@/stores/submission'
 
 import ApiService from '@/common/services/ApiService.js'
 import inputBindingsMixin from '@/common/inputBindingsMixin.js'
-import inputFormatMixin from '@/common/inputFormatMixin.js'
 
 import BackToTopLink from '@/common/components/BackToTopLink.vue'
 
 export default {
-  mixins: [inputBindingsMixin, inputFormatMixin],
+  mixins: [inputBindingsMixin],
```
Comment (lunamoonmoon) [inline app/frontend/src/submissions/components/SubmissionForm/AquiferData.vue:87]: touched submissions files just to remove inputFormatMixin which is not needed now with InputMask

File: app/frontend/src/registry/components/people/OrganizationAdd.vue [hunk 4]
```diff
@@ -1,175 +1,151 @@
...
-            <b-col cols="12" md="6">
-              <b-form-group
-                label="Office telephone number:"
-                label-for="orgAddPhoneInput">
-                <b-form-input
                     id="orgAddPhoneInput"
-                    type="text"
-                    :formatter="formatTel"
-                    lazy-formatter
+                    mask="(999) 999-9999"
```
Comment (lunamoonmoon) [inline app/frontend/src/registry/components/people/OrganizationAdd.vue]: mask="(999) 999-9999" replaces inputFormatMixin function to format into telephone numbers.

**Review by wilwong89 — APPROVED** [review]
